/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;


import JavaMainModel.PatientDirectory;
import JavaMainModel.Person;
import JavaMainModel.PersonDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author girish
 */
public class ShowAllPatient extends javax.swing.JPanel {

    /**
     * Creates new form ShowAllPatient
     */
    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    Person person;
    public ShowAllPatient(PatientDirectory patientDirectory,PersonDirectory personDirectory) {
        initComponents();
        this.patientDirectory=patientDirectory;
        this.personDirectory=personDirectory;
        DisplayData();
    }
     
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSearchAbnormalPtn = new javax.swing.JTable();
        lnlSearch = new javax.swing.JLabel();

        setBackground(new java.awt.Color(180, 207, 234));
        setForeground(new java.awt.Color(180, 207, 234));

        jSearchAbnormalPtn.setBackground(new java.awt.Color(204, 204, 204));
        jSearchAbnormalPtn.setForeground(new java.awt.Color(0, 0, 0));
        jSearchAbnormalPtn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Id", "Patient Name", "Vital Sign", "Age"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane1.setViewportView(jSearchAbnormalPtn);

    lnlSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lnlSearch.setForeground(new java.awt.Color(17, 12, 102));
    lnlSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lnlSearch.setText("All Patients Directory");
    lnlSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        .addComponent(lnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(lnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(57, 57, 57)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(149, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents


    private void DisplayData() {
        try{
        var x = personDirectory.getPersonDirectory();
        DefaultTableModel model = new DefaultTableModel(new Object[]{ "Id", "Person Name", "Contact Number", "Age", "Email", "Contact"}, 0);
        if(x!=null && !x.isEmpty())
        {
            x.forEach(person -> {
            model.addRow(new Object[]
            {person.getPatientID(),person.getName(), person.getCellPhoneNumber(), person.getAge(), person.getEmail(), person.getCellPhoneNumber()});
            
        });
        jSearchAbnormalPtn.setModel(model);
        }
        
        else{
          JOptionPane.showMessageDialog(this,"No Appointment to View");
          return;
        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Please Create an appointment before displaying");
        }

    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jSearchAbnormalPtn;
    private javax.swing.JLabel lnlSearch;
    // End of variables declaration//GEN-END:variables
}
